export const FIRST_NAME = 'Иван';
export const MIDDLE_NAME = 'Александрович';
export const LAST_NAME = 'Якубенко';
export const SHORT_NAME = 'И. А. Якубенко';
export const PENSIA = 1;
export const DOHOD = 13;
export const NDS = DOHOD + PENSIA;
export const NDS_VICHET = 192;
export const NDS_VICHET_LIMIT = 1164;
