name: ContractsApi Deploy to cPanel

on:
  push:
    branches:
      - yakubenka
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout Code 🚚
        uses: actions/checkout@v4
 
      - name: Install ContractsApi Dependencies 📦
        run: npm --prefix ./palasja/ install

      - name: Upload to cPanel 📂
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: 	./contractsApi/
          server-dir: /apitest.palasja.by/
          exclude: |
            **/.git**
            **/.git*/**
            **/node_modules/**
            **/.**