name: Palasja Deploy to cPanel

on:
  [push, workflow_dispatch]:
    branches:
      - yakubenka
      - pavluchenko
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout Code 🚚
        uses: actions/checkout@v4
 
      - name: Install Palasja Dependencies 📦
        run: |
          npm --prefix ./palasja/ install
          npm --prefix ./palasja/ run build

      - name: Upload to cPanel 📂
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: 	./palasja/dist/
          server-dir: /palasja.site/
          exclude: |
            **/.git**
            **/.git*/**
            **/node_modules/**
            **/.**